#
# Module manifest for module 'ExtraLarge'
#
# Generated by: Patrik Husfloen
#
# Generated on: 5-4-2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ExtraLarge.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = '6327d03e-5d72-4f9b-bcd2-a9fc1ea062fe'

# Author of this module
Author = 'Patrik Husfloen'

# Company or vendor of this module
CompanyName = 'ExtraLarge'

# Copyright statement for this module
Copyright = '(c) 2016 Patrik Husfloen. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Create and modify Excel files using PowerShell without any runtime requirements on Microsoft Excel.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '3.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'MSIL'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'EPPlus.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'Add-XLChart.ps1', 'Add-XLSheet.ps1', 'Add-XLTable.ps1', 'Clear-XLRange.ps1', 'EPPlus.dll', 'ExtraLarge.psd1', 'ExtraLarge.psm1', 'Get-XLFile.ps1', 'Get-XLSheet.ps1', 'Join-XLRange.ps1', 'New-XLFile.ps1', 'Save-XLFile.ps1', 'Select-XLRange.ps1', 'Set-XLValue.ps1', 'Split-XLRange.ps1', 'Types.cs'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Excel', 'EPPlus', 'Charts'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/redoz/ExtraLarge/master/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'http://github.com/redoz/ExtraLarge'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

